# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83ac8733622aa1ef5941fff760b51d377743a7741ec86673e1815dc87bb7b33eede67eb4463fb7de6f558dd2a972b5681fa5b4e4072a62c15edac4f0dbecccef

test:
  secret_key_base: 471438004b3fe1871f485b84ecbf9f890e560932d8b7b001e5dc2de2706858b830f78108f17a65ea1977352a479636dd3b8b015c15d601b3bf6e67b4e9788cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
